In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/baddam9/complaintsf/complaints.csv

In [2]:
import pandas as pd
df=pd.read_csv(r"/kaggle/input/datasets/baddam9/complaintsf/complaints.csv")
df

/tmp/ipykernel_112/1938572522.py:2: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r"/kaggle/input/datasets/baddam9/complaintsf/complaints.csv")

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,2023-09-25,Credit reporting or other personal consumer re...,Credit reporting,Problem with a company's investigation into an...,Investigation took more than 30 days,I am listing accounts below that have been rep...,NaN,"EQUIFAX, INC.",TX,75043,NaN,Web,2023-09-25,Closed with non-monetary relief,Yes,7601687
1,2023-09-25,Credit reporting or other personal consumer re...,Credit reporting,Problem with a company's investigation into an...,Investigation took more than 30 days,I am listing accounts below that have been rep...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",TX,75043,NaN,Web,2023-09-25,Closed with non-monetary relief,Yes,7602775
2,2023-09-25,Credit reporting or other personal consumer re...,Credit reporting,Problem with a company's investigation into an...,Investigation took more than 30 days,I am listing accounts below that have been rep...,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,TX,75043,NaN,Web,2023-09-25,Closed with explanation,Yes,7602774
3,2023-10-14,Credit reporting or other personal consumer re...,Credit reporting,Problem with a company's investigation into an...,Investigation took more than 30 days,I am listing accounts below that have been rep...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",TX,75043,NaN,Web,2023-10-14,Closed with non-monetary relief,Yes,7696238
4,2023-10-14,Credit reporting or other personal consumer re...,Credit reporting,Problem with a company's investigation into an...,Investigation took more than 30 days,I am listing accounts below that have been rep...,NaN,"EQUIFAX, INC.",TX,75043,NaN,Web,2023-10-14,Closed with explanation,Yes,7697335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17610157,2023-03-11,"Credit reporting, credit repair services, or o...",Credit reporting,Improper use of your report,Reporting company used your report improperly,"I am a natural person, I am a living human bei...",Company has responded to the consumer and the ...,Experian Information Solutions Inc.,IL,60803,NaN,Web,2023-03-11,Closed with explanation,Yes,6681351
17610158,2023-03-11,"Credit reporting, credit repair services, or o...",Credit reporting,Improper use of your report,Reporting company used your report improperly,NaN,NaN,"EQUIFAX, INC.",MA,01841,NaN,Web,2023-03-11,Closed with explanation,Yes,6681349
17610159,2023-03-11,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,"EQUIFAX, INC.",PA,19139,NaN,Web,2023-03-11,Closed with explanation,Yes,6681559
17610160,2023-03-11,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,PA,19139,NaN,Web,2023-03-11,Closed with non-monetary relief,Yes,6681558
17610161,2023-03-11,"Credit reporting, credit repair services, or o...",Credit reporting,Improper use of your report,Reporting company used your report improperly,NaN,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",MA,01841,NaN,Web,2023-03-11,Closed with non-monetary relief,Yes,6681348

In [3]:
df.shape

(17610162, 16)

In [4]:
df.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Submitted via', 'Date sent to company',
       'Company response to consumer', 'Timely response?', 'Complaint ID'],
      dtype='object')

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isna().sum()

Date received                          0
Product                                0
Sub-product                       235275
Issue                                  6
Sub-issue                         932888
Consumer complaint narrative    13760632
Company public response          7944882
Company                                0
State                              62626
ZIP code                            2382
Tags                            16807619
Submitted via                          0
Date sent to company                   0
Company response to consumer          21
Timely response?                       0
Complaint ID                           0
dtype: int64

In [7]:
df=df.dropna()

In [8]:
df.isna().sum()

Date received                   0
Product                         0
Sub-product                     0
Issue                           0
Sub-issue                       0
Consumer complaint narrative    0
Company public response         0
Company                         0
State                           0
ZIP code                        0
Tags                            0
Submitted via                   0
Date sent to company            0
Company response to consumer    0
Timely response?                0
Complaint ID                    0
dtype: int64

In [9]:
df.describe()

       Complaint ID
count  1.547390e+05
mean   8.307684e+06
std    4.881800e+06
min    1.290282e+06
25%    4.128848e+06
50%    7.231514e+06
75%    1.144179e+07
max    2.474357e+07

In [10]:
df["Product"].value_counts()

Product
Credit reporting, credit repair services, or other personal consumer reports    43553
Credit reporting or other personal consumer reports                             37501
Debt collection                                                                 20402
Checking or savings account                                                     20109
Credit card or prepaid card                                                     10905
Credit card                                                                     10543
Mortgage                                                                         6062
Vehicle loan or lease                                                            3830
Student loan                                                                     1465
Prepaid card                                                                      272
Payday loan, title loan, or personal loan                                          60
Payday loan, title loan, personal loan, or advance loan                            37
Name: count, dtype: int64

In [11]:
df.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Submitted via', 'Date sent to company',
       'Company response to consumer', 'Timely response?', 'Complaint ID'],
      dtype='object')

In [12]:
df['Product'].unique()

array(['Debt collection', 'Credit card', 'Mortgage',
       'Checking or savings account', 'Vehicle loan or lease',
       'Student loan',
       'Credit reporting or other personal consumer reports',
       'Prepaid card',
       'Credit reporting, credit repair services, or other personal consumer reports',
       'Payday loan, title loan, personal loan, or advance loan',
       'Credit card or prepaid card',
       'Payday loan, title loan, or personal loan'], dtype=object)

In [13]:
df['Issue'].unique()

array(['Attempts to collect debt not owed',
       'Other features, terms, or problems',
       'Trouble during payment process', 'Managing an account',
       'Problem with a lender or other company charging your account',
       'Closing on a mortgage', 'Closing your account',
       'Problem caused by your funds being low',
       'Credit monitoring or identity theft protection services',
       'False statements or representation', 'Getting a credit card',
       'Problem with a purchase shown on your statement',
       'Communication tactics',
       'Problems at the end of the loan or lease',
       'Struggling to pay mortgage', 'Struggling to pay your loan',
       'Advertising and marketing, including promotional offers',
       'Struggling to repay your loan', 'Fees or interest',
       'Trouble using your card', 'Closing an account',
       'Problem when making payments',
       'Took or threatened to take negative or legal action',
       'Incorrect information on your report', 'Opening an account',
       'Getting a loan or lease',
       'Applying for a mortgage or refinancing an existing mortgage',
       'Managing the loan or lease',
       "Problem with a company's investigation into an existing problem",
       'Written notification about debt', 'Trouble using the card',
       'Getting a loan', 'Improper use of your report',
       'Dealing with your lender or servicer',
       'Unable to get your credit report or credit score',
       'Problem with a purchase or transfer', 'Repossession',
       'Problem getting a card or closing an account',
       'Electronic communications',
       'Threatened to contact someone or share information improperly',
       'Struggling to pay your bill', 'Issue with income share agreement',
       "Problem with a credit reporting company's investigation into an existing problem",
       'Issue where my lender is my school', 'Advertising',
       "Problem with a company's investigation into an existing issue",
       'Identity theft protection or other monitoring services',
       'Problem with overdraft', 'Disclosure verification of debt',
       'Dealing with my lender or servicer',
       "Cont'd attempts collect debt not owed",
       'Taking/threatening an illegal action',
       'Improper contact or sharing of info', "Can't repay my loan"],
      dtype=object)

In [14]:
df['Sub-issue'].unique()

array(['Debt is not yours', 'Other problem',
       'Escrow, taxes, or insurance', 'Deposits and withdrawals',
       'Fees charged', 'Transaction was not authorized',
       'Delays with the closing process', 'Company closed your account',
       'Paying off the loan', 'Late or other fees',
       "Didn't receive services that were advertised",
       'Problem using a debit or ATM card',
       'Attempted to collect wrong amount',
       'Card opened without my consent or knowledge',
       "Credit card company isn't resolving a dispute about a purchase on your statement",
       'Used obscene, profane, or other abusive language',
       'Unable to receive car title or other problem after the loan is paid off',
       'Problem with rewards from credit card',
       'Problem with balance transfer',
       'Excess mileage, damage, or wear fees, or other problem after the lease is finished',
       'Foreclosure', 'Add-on products and services',
       'Denied request to lower payments',
       'An existing modification, forbearance plan, short sale, or other loss mitigation relief',
       'Loan sold or transferred to another company',
       "Didn't receive advertised or promotional terms",
       "Can't temporarily delay making payments", 'Problem with fees',
       "Can't use card to make purchases",
       'Sent card you never applied for',
       'Debt was result of identity theft', 'Banking errors',
       'Problem during payment process',
       'Sued you without properly notifying you of lawsuit',
       'Account information incorrect', 'Payment process',
       'Problem with customer service',
       'Trying to communicate with the company to fix an issue while managing or servicing your loan',
       'Unable to open an account', 'Charged too much interest',
       'Money was taken from your account on the wrong day or for the wrong amount',
       'Loan opened without my consent or knowledge', 'Cashing a check',
       'Delays in the application process',
       'Funds not received from closed account', 'Problem with renewal',
       'Funds not handled or disbursed as instructed',
       'High-pressure sales tactics',
       'Collected or attempted to collect exempt funds',
       'Overdrafts and overdraft fees', 'Problem with fees charged',
       "Didn't receive terms that were advertised",
       "Can't close your account",
       'You told them to stop contacting you, but they keep trying',
       'Card was charged for something you did not purchase with the card',
       'Their investigation did not fix an error on your report',
       'Trying to communicate with the company to fix an issue related to modification, forbearance, short sale, deed-in-lieu, bankruptcy, or foreclosure',
       'Frequent or repeated calls', 'Application denied',
       'Debt was paid',
       "Didn't receive enough information to verify debt",
       'Was not notified of investigation status or results',
       'Problem accessing account',
       'Problem making or receiving payments',
       'Delay in processing application',
       'Trouble using the card to pay a bill',
       'Confusing or misleading advertising about the credit card',
       'Problem with personal statement of dispute', 'Billing problem',
       'Account status incorrect',
       'Problem with additional products or services purchased with the loan',
       "Didn't receive notice of right to dispute",
       'Public record information inaccurate', 'Deposits or withdrawals',
       "Can't stop withdrawals from your account",
       'Unexpected increase in interest rate',
       'Reporting company used your report improperly',
       'Difficulty submitting a dispute or getting information about a dispute over the phone',
       'Applying for or obtaining a modification, forbearance plan, short sale, or deed-in-lieu',
       'Trouble with how payments are being handled', 'Privacy issues',
       'Closing disclosure or other related disclosures',
       'Application denials', 'Non-sufficient funds and associated fees',
       'Problem getting your free annual credit report',
       "Card company isn't resolving a dispute about a purchase or transfer",
       "Notification didn't disclose it was an attempt to collect a debt",
       'Threatened to sue you for very old debt',
       "Can't get other flexible options for repaying your loan",
       'Problem while selling or giving up the vehicle',
       'Threatened or suggested your credit would be damaged',
       'Trying to communicate with the company to fix an issue with the loan closing',
       'Impersonated attorney, law enforcement, or government official',
       'Problem with the interest rate',
       'Damage caused or loss of personal items in vehicle during the actual repossession',
       'Indicated you were committing crime by not paying debt',
       'Problem getting a working replacement card',
       'Fees or costs after closing', 'Personal information incorrect',
       'Received bad information about your loan',
       'Changes in loan terms during or after closing',
       'Account opened without my consent or knowledge',
       'Trouble using the card to spend money in a store or online',
       'Problem with paying off the loan',
       'Problem canceling credit monitoring or identify theft protection service',
       'Billing dispute for services',
       'Lender trying to repossess or disable the vehicle',
       'Problem with cash advances', 'Called before 8am or after 9pm',
       'Trouble getting a working replacement card',
       'Overcharged for something you did purchase with the card',
       'You never received your bill or did not know a payment was due',
       'Charged for a purchase or transfer you did not make with the card',
       'Confusing or misleading advertising or marketing',
       'Loan balance remaining after the vehicle is repossessed and sold',
       'Frequent or repeated messages',
       'Private mortgage insurance (PMI)',
       'Fees or costs during the application process',
       "Credit card company won't increase or decrease your credit limit",
       'Trying to communicate with the company to fix an issue with the application process',
       'Termination fees or other problem when ending the lease early',
       'Bounced checks or returned payments', 'Voluntary repossession',
       'Confusing or missing disclosures',
       'Talked to a third-party about your debt',
       'Negative impact of inaccurate appraisal',
       'Debt was already discharged in bankruptcy and is no longer owed',
       'Fee problem', 'Interest rate',
       'Information belongs to someone else',
       'Fees charged for closing account',
       "Credit card company won't work with you while you're going through financial hardship",
       'Seized or attempted to seize your property',
       "Credit inquiries on your report that you don't recognize",
       'Need information about your loan balance or loan terms',
       'Notice to repossess',
       'Contacted you after you asked them to stop', 'Payment issues',
       'Deficiency balance after repossession',
       'Problem with forgiveness, cancellation, or discharge',
       'Other problem getting your report or credit score',
       'Changes in terms mid-deal or after closing',
       'Account reinstatement or redemption after repossession',
       'Problem using the card to withdraw money from an ATM',
       'Filed for bankruptcy', 'Investigation took more than 30 days',
       'Information is incorrect',
       'Problem with additional add-on products or services purchased with the loan',
       'Problem with signing the paperwork',
       'Account sold or transferred to another company',
       'Report provided to employer without your written authorization',
       'Problem with fees or penalties', 'Credit denial',
       'Problem lowering your monthly payments', 'Trouble closing card',
       'Old information reappears or never goes away',
       'Problem when attempting to purchase vehicle at the end of the lease',
       'Keep getting calls about your loan', 'Lien release',
       'Credit card company forcing arbitration',
       'Changes in loan terms during the application process',
       'Trouble getting information about the card',
       'Sued you in a state where you do not live or did not sign for the debt',
       'Contacted before 8am or after 9pm',
       'Problem related to refinancing', 'Company explaining amount owed',
       'Issues with fees connected to the loan',
       'Threatened to arrest you or take you to jail if you do not pay',
       "Don't agree with the fees charged", 'Co-signer',
       'Company communicating payment assistance or payment extension options',
       'Loan estimate or other related disclosures',
       'Problem after you declared or threatened to declare bankruptcy',
       'Trouble getting, activating, or registering a card',
       'Told you not to respond to a lawsuit they filed against you',
       'Changes in terms from what was offered or advertised',
       'Problem with a trade-in',
       'Overcharged for a purchase or transfer you did make with the card',
       'Card opened as result of identity theft or fraud',
       'Received unsolicited financial product or insurance offers after opting out',
       'Account opened as a result of fraud',
       "Don't want a card provided by your employer or the government",
       'Fraudulent loan', 'Received unwanted marketing or advertising',
       'Information is missing that should be on the report',
       'Problem with product or service terms changing',
       'Information that should be on the report is missing',
       'Problem with direct deposit', 'Problem with convenience check',
       'Contacted your employer',
       'Contacted you instead of your attorney',
       'Confusing or misleading advertising about the card',
       'Issues with financial aid services',
       'Problem with your payment plan', 'Billing or statement issues',
       'Denied loan', 'Problem extending the lease',
       'Did not receive car title',
       'Cannot graduate, receive diploma, or get transcript due to money owed',
       'Threatened to turn you in to immigration or deport you',
       'Problem with a check written from your prepaid card account',
       'Setting up an escrow account for taxes and insurance',
       'Marketing or disclosure issues',
       'Confusing or misleading advertising',
       'Qualified for a better loan than the one offered',
       'Dealing with provider of income share agreement',
       'Problem adding money', 'Overdraft charges',
       'Trouble using the card to send money to another person',
       'High pressure sales tactics or recruiting',
       'Right to dispute notice not received',
       'Having problems with customer service',
       "Indicated shouldn't respond to lawsuit",
       'Threatened to take legal action',
       'Impersonated an attorney or official',
       'Not given enough info to verify debt',
       'Called after sent written cease of comm', 'Debt is not mine',
       'Debt resulted from identity theft',
       'Not disclosed as an attempt to collect',
       'Received bad information about my loan',
       'Threatened arrest/jail if do not pay',
       'Trouble with how payments are handled',
       'Sued w/o proper notification of suit',
       "Sued where didn't live/sign for debt",
       'Debt was discharged in bankruptcy',
       'Seized/Attempted to seize property',
       'Talked to a third party about my debt',
       'Used obscene/profane/abusive language',
       'Need information about my balance/terms',
       'Attempted to/Collected exempt funds',
       'Threatened to sue on too old debt',
       "Can't decrease my monthly payments",
       'Qualify for a better loan than offered',
       "Don't agree with fees charged",
       'Indicated committed crime not paying',
       "Can't temporarily postpone payments",
       'Contacted employer after asked not to',
       'Called outside of 8am-9pm', 'Contacted me after I asked not to',
       "Can't qualify for a loan", "Can't get flexible payment options",
       'Contacted me instead of my attorney',
       'Keep getting calls about my loan'], dtype=object)

In [15]:
df["Consumer complaint narrative"].unique()

array(['RE : FRAUDULENT ACCOUNTS/ IDENTITY THEFT / UNVERIFIABLE DEBT REPORTING To Whom It May Concern : I am formally disputing the account listed on my consumer report as fraudulent, inaccurate, and unverifiable. I have never entered into a contractual agreement with these companies, nor have I signed any original contract bearing my wet-ink signature obligating me to these alleged debts. Furthermore, I have reason to believe these accounts are connected to identity theft and/or unlawful reporting practices. I previously submitted identity theft documentation and disputes regarding these accounts, yet they continue to appear on my consumer report in violation of the Fair Credit Reporting Act ( FCRA ). The following accounts are disputed in their entirety : CREDIT CONTROL , LLC Any associated collection accounts, late payments, charge-offs, or related reporting connected to these alleged debt I specifically dispute the accuracy, ownership, and legal enforceability of these accounts. Additionally, the alleged original creditor reportedly sold or transferred the debt to third-party collection agencies. However, no lawful validation or contractual proof has ever been provided to me demonstrating : That I entered into any agreement with these companies That the debt was lawfully assigned That the collector possesses legal authority to collect or report the debt That proper verification procedures were followed Under the Fair Credit Reporting Act, including but not limited to : 15 U.S.C. 1681e ( b ) 15 U.S.C. 1681i 15 U.S.C. 1681b 15 U.S.C. 1681c-2 you are required to conduct a reasonable investigation and remove any information that can not be properly verified. Therefore, I demand the following : 1. Immediate deletion of all fraudulent, inaccurate, unauthorized, and unverifiable accounts from my consumer reports 2. Removal of all associated late payments, charge-offs, collections, and negative reporting 3. Removal of all unauthorized inquiries lacking permissible purpose 4. Copies of all original signed contracts bearing my wet-ink signature 5. Complete chain of assignment and ownership of the alleged debt 6. Full accounting records and payment histories 7. The method of verification used during your investigation 8. The name, title, address, and phone number of every person or entity contacted during reinvestigation If these items can not be fully verified with competent legal documentation, they must be permanently deleted from my consumer file immediately. Continued reporting of fraudulent or unverified information after notice may constitute willful noncompliance under the FCRA and may subject the reporting parties to liability for damages. Sincerely, XXXX XXXX XXXX',
       "I received an email stating my Synchrony XXXX XXXX Credit Card payment was due. I paid it right away. The interest rate is 9.9 % and payments are to be {$120.00}. until the balance is paid off. It showed on the account manager that I still owed {$120.00}. The payment was credited to the previous month. I was mailed a refund check and I resubmitted the payment. The next month my amount due was {$150.00}. I paid it. This month they are billing me {$150.00}. I called the customer service line and spoke to XXXX. She did not know why this happened and was guessing that the promotional deal was only for 12, 36 or 48 months. Then she suggested that I wasn't paying interest until now. None of this is true. Additional information provided by consumer : XXXX Consumer says this complaint is about Synchrony Bank.",
       'I am filing a complaint regarding the servicing of my mortgage loan and escrow account with NewRez mortgage. I am XXXX XXXX XXXX XXXX XXXX XXXX veteran and do not pay the full amount of property taxes listed on the website. My mortgage servicer appears to have overpaid my property taxes during XXXX, which depleted or negatively impacted my escrow account. As a result, the company is now demanding substantially higher monthly mortgage payments to recover an alleged escrow shortage. Despite repeated attempts to obtain information and clarification, the servicer has failed to provide adequate documentation, clear accounting records, or current mortgage statements explaining the shortage and payment increase. I am requesting : - A full escrow accounting and escrow analysis for XXXX, XXXX and XXXX - Documentation of all property tax disbursements made on my behalf - A detailed explanation of how the escrow shortage was calculated - Copies of all mortgage statements and payment change notices- Correction of any improper escrow charges or shortages resulting from tax overpayments- Investigation into the servicers failure to provide timely and accurate account information - correction of my account to all credit reporting agencies showing me in arrears This situation has caused significant financial hardship and uncertainty regarding my mortgage obligations ; has severely negatively affected my credit rating. I believe the servicer may have mishandled escrow funds and failed to provide required servicing disclosures and statements. I respectfully request that the Consumer Financial Protection Bureau investigate this matter and require the mortgage servicer to provide a full accounting and correct any errors associated with the escrow account and property tax',
       ...,
       'A few months ago I reviewed a copy of my XXXX and TransUnion credit reports where I noticed an account that is reporting inaccurately. It is showing misleading information, since it is showing the account as Paid/ Paying as Agreed but has late payments listed in the history. This misleading data is causing great harm to my credit score and its detrimental to my financial well being. I contacted each bureau by mail and phone to have them correct the issue, but they have not done anything. As I am aware by researching, these inaccuracies on my report are a violation of the Fair Credit Billing Act ( FCBA ), 15 U.S. Code 1666-1666j the creditor must provide me with PROOF that I was indeed late but they CAN NOT. And it also fall under 15 U.S Code 1666 ( b ) billing error. \nXXXX and TransUnion are violating the following FCRA law by reporting this inaccurate data : : Misleading False Reporting : This account is negatively and inaccurately reporting, failing to comply with 15 U.S.C 1681. Per CRSA enacted, CDIA implemented laws, any and all reporting must be deleted if not Proven CERTIFIABLY fully true, correct, complete, timely, of known ownership and responsibility but also fully XXXX XXXX compliant. Provider Claims Late Payment yet has NOT PROVEN even the compliance of its reporting much less any aspect of determined truth of facts else wise required by obligatory regulations. These bureaus are violating multiple FCRA, FCBA laws and i want them to correct this inaccurate data as soon as possible because it is detrimental to my credit score, which is causing me great stress to me and my family and affecting our ability to grow financially and obtain a home loan.',
       "Opened account with Bank of America in early 2022. Did so online. On XX/XX/22 I transferred XXXX dollars into the account. On XX/XX/XXXX I transferred {$240.00} into the account. And finally on XX/XX/XXXX I transferred {$220.00} into the account for a total of {$660.00}. With the addition of my initial deposit of {$1200.00} the account had an amount of {$1600.00}. 3 days after the final deposit of {$660.00} my account was closed. I did not receive any paperwork until after the account was closed. No one called No One reached out to me in any way to inform me about any issues with my account. I have scheduled several appointments and had several sit-downs with different members of this Bank of America . During my initial visit I was told my account was closed due to a potential fraud case as they had found a Utah address under my name. I informed them that I had just moved in from Utah and when I had set up my account I had used a Utah driver 's license. I was told me to call XXXX and that they would be able to assist me. When I call that number they told me that the Bank of America held my account would need to be the ones to pay out the funds and that I would need to be in contact with them. When I reached back out to Bank of America I was given a different number to call that number being XXXX. This number also referred me back to my Bank of America. It is now coming up on one year on waiting to be refunded so far I have been refunded my initial deposit of {$1000.00} but, have yet to receive the other XXXX dollars.",
       'Fraud account already provided documents to creditors and they assured me they would remove from all 3 credit buearus. My score use to be excellent XXXX until this fraud occurred by Ashley furniture. Identity stolen to open fraud account'],
      dtype=object)

# Data Preprocessing

In [16]:
import nltk
from nltk.corpus import stopwords
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [17]:
import regex as re
stop_words=set(stopwords.words("english"))

def text_preprocessing(text):
    text=text.lower()

    text = re.sub(r'\bx+\b', '', text)
    
    text = re.sub(r'[$₹€£]\s?[\d,]+(?:\.\d+)?', ' money ', text)
    
    text=re.sub(r'[^a-z0-9\s]','',text)
    
    tokens=text.split()

    preprocessed_text=[w for w in tokens if w not in stop_words]

    return ' '.join(preprocessed_text)

In [18]:
df["Consumer complaint narrative"]=df["Consumer complaint narrative"].apply(text_preprocessing)

/tmp/ipykernel_112/1071827568.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Consumer complaint narrative"]=df["Consumer complaint narrative"].apply(text_preprocessing)

df["Consumer complaint narrative"][0]

df["Consumer complaint narrative"][1]

# splitting the data into input and output(for problem classification)

In [19]:
df.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Submitted via', 'Date sent to company',
       'Company response to consumer', 'Timely response?', 'Complaint ID'],
      dtype='object')

In [20]:
x=df["Consumer complaint narrative"]
y=df["Product"]

In [21]:
y1=df["Issue"]
y1

65                          Attempts to collect debt not owed
67                         Other features, terms, or problems
78                             Trouble during payment process
94                                        Managing an account
158                            Trouble during payment process
                                  ...
17610029                 Incorrect information on your report
17610034    Problem with a credit reporting company's inve...
17610060    Problem with a credit reporting company's inve...
17610083                                   Closing an account
17610107                    Attempts to collect debt not owed
Name: Issue, Length: 154739, dtype: object

In [22]:
y2=df["Sub-issue"]
y2

65                                          Debt is not yours
67                                              Other problem
78                                Escrow, taxes, or insurance
94                                   Deposits and withdrawals
158                                              Fees charged
                                  ...
17610029                       Personal information incorrect
17610034    Their investigation did not fix an error on yo...
17610060    Their investigation did not fix an error on yo...
17610083                          Company closed your account
17610107                    Debt was result of identity theft
Name: Sub-issue, Length: 154739, dtype: object

In [23]:
y.value_counts()

Product
Credit reporting, credit repair services, or other personal consumer reports    43553
Credit reporting or other personal consumer reports                             37501
Debt collection                                                                 20402
Checking or savings account                                                     20109
Credit card or prepaid card                                                     10905
Credit card                                                                     10543
Mortgage                                                                         6062
Vehicle loan or lease                                                            3830
Student loan                                                                     1465
Prepaid card                                                                      272
Payday loan, title loan, or personal loan                                          60
Payday loan, title loan, personal loan, or advance loan                            37
Name: count, dtype: int64

In [24]:
y1.value_counts()

Issue
Incorrect information on your report                                                39435
Improper use of your report                                                         18584
Problem with a credit reporting company's investigation into an existing problem    12468
Managing an account                                                                 10669
Problem with a company's investigation into an existing problem                      9034
Attempts to collect debt not owed                                                    8541
Problem with a purchase shown on your statement                                      6857
Problem caused by your funds being low                                               3171
Trouble during payment process                                                       3122
Fees or interest                                                                     2941
Written notification about debt                                                      2842
Other features, terms, or problems                                                   2717
Problem with a lender or other company charging your account                         2537
Closing an account                                                                   2413
False statements or representation                                                   2400
Took or threatened to take negative or legal action                                  2122
Getting a credit card                                                                1907
Problem when making payments                                                         1791
Communication tactics                                                                1733
Unable to get your credit report or credit score                                     1713
Closing your account                                                                 1633
Cont'd attempts collect debt not owed                                                1470
Managing the loan or lease                                                           1427
Credit monitoring or identity theft protection services                              1351
Struggling to pay mortgage                                                           1246
Opening an account                                                                   1224
Trouble using your card                                                               996
Advertising and marketing, including promotional offers                               985
Dealing with your lender or servicer                                                  967
Problems at the end of the loan or lease                                              815
Applying for a mortgage or refinancing an existing mortgage                           659
Closing on a mortgage                                                                 494
Struggling to pay your loan                                                           494
Getting a loan or lease                                                               470
Disclosure verification of debt                                                       450
Repossession                                                                          314
Threatened to contact someone or share information improperly                         298
Trouble using the card                                                                278
Problem with a purchase or transfer                                                   270
Problem with a company's investigation into an existing issue                         257
Struggling to pay your bill                                                           248
Struggling to repay your loan                                                         245
Problem getting a card or closing an account                                          225
Taking/threatening an illegal action                                                  216
Electronic communications                                                             168
Improper contact or sharing of info                                                   162
Identity theft protection or other monitoring services                                149
Dealing with my lender or servicer                                                    100
Advertising                                                                            48
Getting a loan                                                                         39
Can't repay my loan                                                                    31
Problem with overdraft                                                                  7
Issue with income share agreement                                                       4
Issue where my lender is my school                                                      2
Name: count, dtype: int64

In [25]:
y2.value_counts()

Sub-issue
Their investigation did not fix an error on your report                  14738
Information belongs to someone else                                      12817
Reporting company used your report improperly                            12509
Account information incorrect                                            10456
Account status incorrect                                                  8696
                                                                         ...
Qualified for a better loan than the one offered                             1
Cannot graduate, receive diploma, or get transcript due to money owed        1
Billing or statement issues                                                  1
Issues with financial aid services                                           1
Marketing or disclosure issues                                               1
Name: count, Length: 244, dtype: int64

In [26]:
df.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Submitted via', 'Date sent to company',
       'Company response to consumer', 'Timely response?', 'Complaint ID'],
      dtype='object')

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le_problem = LabelEncoder()
le_issue = LabelEncoder()
le_subissue = LabelEncoder()

y_problem = le_problem.fit_transform(df["Product"])
y_issue = le_issue.fit_transform(df["Issue"])
y_subissue = le_subissue.fit_transform(df["Sub-issue"])

x_train,x_test,y_problem_train,y_problem_test=train_test_split(df["Consumer complaint narrative"],y_problem,test_size=0.20,random_state=23)

x_train,x_test,y_issue_train,y_issue_test= train_test_split(df["Consumer complaint narrative"],y_issue,test_size=0.20,random_state=23)

x_train,x_test,y_subissue_train,y_subissue_test = train_test_split(df["Consumer complaint narrative"],y_subissue,test_size=0.20,random_state=23)

In [29]:
x_train, x_test, \
y_problem_train, y_problem_test, \
y_issue_train, y_issue_test, \
y_subissue_train, y_subissue_test = train_test_split(
    df["Consumer complaint narrative"],
    y_problem,
    y_issue,
    y_subissue,
    test_size=0.20,
    random_state=23
)

In [30]:
x_train.shape, x_test.shape, y_problem_train.shape, y_problem_test.shape, y_issue_train.shape, y_issue_test.shape,y_subissue_train.shape,y_subissue_test.shape

((123791,),
 (30948,),
 (123791,),
 (30948,),
 (123791,),
 (30948,),
 (123791,),
 (30948,))

In [31]:
df.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Submitted via', 'Date sent to company',
       'Company response to consumer', 'Timely response?', 'Complaint ID'],
      dtype='object')

In [32]:
x_train

4336597     date birthxxxxxxxx fl dear transunion writing ...
4604942     applied credit card key bank discriminatedi to...
16870906    2022 several letters mailed regarding alleged ...
9965513     dispute collection account request immediate r...
16062183    transunion reporting 5 late account account su...
                                  ...
4227935     starting date written letters us bank letters ...
11360223    data breach affected credit report accounts pa...
4202734     2022 son parents joint account owners due call...
16349049    2021 attempted cash usps money order account b...
15509959    hi 2019 purchased used car az tried buy gap in...
Name: Consumer complaint narrative, Length: 123791, dtype: object

# Tokenization

In [33]:
train_sentence=[sentence.split() for sentence in x_train]
print(train_sentence[0])

['date', 'birthxxxxxxxx', 'fl', 'dear', 'transunion', 'writing', 'request', 'investigation', 'following', 'information', 'transunion', 'credit', 'report', 'dispute', 'alleged', 'chargeoff', 'obligation', 'original', 'alleged', 'creditor', 'incorrect', 'following', 'identifying', 'information', 'error', 'account', 'date', 'incorrect', 'reporting', 'explanation', 'dispute', 'victim', 'identity', 'theft', 'open', 'account', 'support', 'claim', 'attached', 'documentation', 'including', 'copy', 'credit', 'report', 'identity', 'theft', 'complaint', 'drivers', 'license', 'ssn', 'card', 'please', 'let', 'know', 'additional', 'information', 'necessary', 'remove', 'chargeoff', 'records', 'appreciate', 'assistance', 'sincerely']

# Vectorization

In [34]:
from gensim.models import FastText
fasttext=FastText(min_count=2,window=10,vector_size=100,workers=5,epochs=5)

In [35]:
fasttext.build_vocab(train_sentence)

In [36]:
print(fasttext.wv)

FastTextKeyedVectors<vector_size=100, 41575 keys>

In [37]:
len(train_sentence)

123791

In [38]:
fasttext.train(train_sentence,total_examples=fasttext.corpus_count,epochs=5)

(55197008, 60353920)

# creating tokenizer

In [39]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [40]:
len(train_sentence)

123791

In [41]:
num_words=20000

tokenizer=Tokenizer(num_words=num_words,oov_token="<oov>")

tokenizer.fit_on_texts(x_train)

In [42]:
train_seq=tokenizer.texts_to_sequences(x_train)
test_seq=tokenizer.texts_to_sequences(x_test)
print(train_seq[0])

[38, 1, 1151, 751, 61, 209, 40, 90, 114, 5, 61, 2, 6, 21, 310, 654, 666, 137, 310, 148, 208, 114, 1601, 5, 258, 3, 38, 208, 7, 432, 21, 362, 75, 91, 179, 3, 561, 122, 164, 118, 191, 158, 2, 6, 75, 91, 44, 1356, 713, 1103, 11, 49, 481, 143, 325, 5, 693, 89, 654, 257, 925, 412, 588]

In [43]:
len(train_seq[0])

63

In [44]:
len(train_seq[1])

37

In [45]:
pd.DataFrame(train_seq).describe()

,0,1,2,3,4,5,6,7,8,9,...,2910,2911,2912,2913,2914,2915,2916,2917,2918,2919
count,123772.000000,123738.000000,123654.000000,123452.000000,123101.000000,122613.000000,121964.000000,121257.000000,120489.000000,119683.000000,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
mean,701.905213,684.568791,702.044746,697.681463,695.827402,703.209635,702.347537,707.147447,709.195180,706.095920,...,1487.0,62.0,1002.0,957.0,6.0,9.0,1487.0,62.0,163.0,1452.0
std,1578.618858,1637.259610,1706.578115,1705.621891,1659.628628,1671.987455,1667.832528,1689.414999,1645.809509,1636.166738,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1487.0,62.0,1002.0,957.0,6.0,9.0,1487.0,62.0,163.0,1452.0
25%,59.000000,44.000000,30.000000,28.000000,37.000000,31.000000,31.000000,35.000000,35.000000,35.000000,...,1487.0,62.0,1002.0,957.0,6.0,9.0,1487.0,62.0,163.0,1452.0
50%,230.000000,153.000000,145.000000,155.000000,162.000000,173.000000,177.000000,172.000000,179.000000,186.000000,...,1487.0,62.0,1002.0,957.0,6.0,9.0,1487.0,62.0,163.0,1452.0
75%,589.000000,563.000000,564.000000,579.000000,603.000000,591.000000,596.000000,595.000000,646.000000,612.000000,...,1487.0,62.0,1002.0,957.0,6.0,9.0,1487.0,62.0,163.0,1452.0
max,19940.000000,19978.000000,19988.000000,19914.000000,19950.000000,19991.000000,19993.000000,19984.000000,19974.000000,19961.000000,...,1487.0,62.0,1002.0,957.0,6.0,9.0,1487.0,62.0,163.0,1452.0

# Padding

In [46]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [47]:
max_len=200
x_train_pad=pad_sequences(train_seq,maxlen=max_len,padding="pre",truncating="post")
x_test_pad=pad_sequences(test_seq,maxlen=max_len,padding="pre",truncating="post")

In [48]:
print(x_train_pad[0])
print(x_train_pad[1])

[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0   38    1 1151
  751   61  209   40   90  114    5   61    2    6   21  310  654  666
  137  310  148  208  114 1601    5  258    3   38  208    7  432   21
  362   75   91  179    3  561  122  164  118  191  158    2    6   75
   91   44 1356  713 1103   11   49  481  143  325    5  693   89  654
  257  925  412  588]
[    0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0   285     2    11  1768     8
     1    17   105  3855    73     2     6   105   857    17   105     1
   105     1   982   219  1387    41   404    25    33 18379    17   179
     3   232   281   618     1     2   105   190]

In [49]:
print(x_test_pad.shape)

(30948, 200)

# creating embedding matrix

In [50]:
embedding_dim=100
vocab_size=40000

embedding_matrix=np.zeros((vocab_size,embedding_dim))

word_index=tokenizer.word_index
word_index

for word,index in word_index.items():
    if index>=vocab_size:
        continue

    if word in fasttext.wv:
        embedding_matrix[index]=(fasttext.wv[word])

In [51]:
embedding_matrix

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.94791092e-03,  4.07958329e-02, -1.51041761e-01, ...,
        -9.23775658e-02,  5.41675724e-02,  1.38436824e-01],
       [-1.57320273e+00, -9.26237285e-01, -3.06905955e-01, ...,
         4.62651539e+00,  2.82865912e-01,  4.49257135e+00],
       ...,
       [ 4.65071589e-01, -7.02016413e-01,  2.39314985e+00, ...,
         1.76542118e-01,  2.06767249e+00,  2.89027977e+00],
       [-4.73977149e-01, -6.17354810e-01,  9.35867131e-01, ...,
         2.08927536e+00,  8.33458364e-01, -1.05656445e+00],
       [ 1.61413193e-01,  1.24121845e+00, -8.26090574e-01, ...,
         1.38378942e+00,  1.21397614e+00,  7.74404943e-01]])

In [52]:
import pickle 
with open(r"C:\Users\PRAVALLIKA\Downloads\nlp\nlp.pkl","wb") as f:
    pickle.dump(tokenizer,f)

In [53]:
with open("label_encoders.pkl", "wb") as f:
    pickle.dump({
        "problem": le_problem,
        "issue": le_issue,
        "subissue": le_subissue
    }, f)

print("Model and preprocessing objects saved successfully!")

Model and preprocessing objects saved successfully!

# Model Building

In [54]:
from keras.models import Sequential,Model

from keras.layers import Input,Embedding,Dense,Dropout,Bidirectional,LSTM

In [55]:
len(df["Product"].unique())

12

In [56]:
len(df["Issue"].unique())

54

In [57]:
len(df["Sub-issue"].unique())

244

In [58]:
num_classes = len(np.unique(y_problem_train))
num_classes

12

In [59]:
inputs = Input(shape=(x_train_pad.shape[1],))

X = Embedding(input_dim=vocab_size,output_dim=embedding_dim, weights=[embedding_matrix],trainable=False)(inputs)

x1 = Bidirectional(LSTM(128))(X)
x1 = Dropout(0.30)(x1)

x2 = Dense(128,activation="relu")(x1)
x2 = Dropout(0.30)(x2)

x3 = Dense(64,activation="relu")(x2)
x3 = Dropout(0.20)(x3)


Problem_output = Dense(12,activation="softmax",name="problem")(x3)


model = Model(inputs=inputs,outputs=[Problem_output])
model.summary()

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1790505208.369744     112 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13756 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1790505208.372587     112 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13756 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 200)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding (Embedding)           │ (None, 200, 100)       │     4,000,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ (None, 256)            │       234,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ problem (Dense)                 │ (None, 12)             │           780 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,276,428 (16.31 MB)

 Trainable params: 276,428 (1.05 MB)

 Non-trainable params: 4,000,000 (15.26 MB)

In [60]:
import tensorflow as tf

In [61]:
model.compile(optimizer="adam",loss=["sparse_categorical_crossentropy"],metrics=["accuracy"])

In [62]:
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

In [63]:
problem_class_weights= compute_class_weight(class_weight="balanced",y=y_problem_train,classes=np.unique(y_problem_train))
print(problem_class_weights)

[6.40461704e-01 1.22110756e+00 1.17213006e+00 3.43806588e-01
 2.96281138e-01 6.34045278e-01 2.15363605e+00 2.39905039e+02
 3.22372396e+02 4.54445668e+01 8.74971727e+00 3.35913926e+00]

In [64]:
classes=np.unique(y_problem_train)
problem_class_weights = dict(zip(classes, problem_class_weights))

In [65]:
from tensorflow.keras.callbacks import EarlyStopping

In [66]:
early_stop = EarlyStopping(monitor="accuracy",patience=10,min_delta=0.0001,restore_best_weights=True)

In [67]:
from tensorflow.keras.callbacks import ModelCheckpoint
checkpoint = ModelCheckpoint(
    filepath='best_model.keras',  # Where to save the file
    monitor='val_loss',  # Metric to watch
    mode='min',  # 'max' for accuracy, 'min' for loss
    save_best_only=True,  # Only save when the model improves
    verbose=1,
)

In [68]:
from sklearn.metrics import f1_score

class F1Callback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        pred = np.argmax(self.model.predict(x_test_pad, verbose=0), axis=1)
        f1 = f1_score(y_problem_test, pred, average="macro")
        print("F1 Score:", f1)

In [69]:
model.fit(x_train_pad,y_problem_train,validation_data=(x_test_pad,y_problem_test),class_weight=problem_class_weights,callbacks=[early_stop,checkpoint,F1Callback()],epochs=20,batch_size=50)

Epoch 1/20
2475/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.2661 - loss: 2.2749
Epoch 1: val_loss improved from None to 1.79323, saving model to best_model.keras

Epoch 1: finished saving model to best_model.keras
F1 Score: 0.26994587699332945
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 63s 23ms/step - accuracy: 0.2847 - loss: 2.1163 - val_accuracy: 0.2847 - val_loss: 1.7932
Epoch 2/20
2474/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.3112 - loss: 1.8277
Epoch 2: val_loss improved from 1.79323 to 1.51646, saving model to best_model.keras

Epoch 2: finished saving model to best_model.keras
F1 Score: 0.33312729852028655
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 57s 23ms/step - accuracy: 0.3299 - loss: 1.8463 - val_accuracy: 0.3993 - val_loss: 1.5165
Epoch 3/20
2474/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3711 - loss: 1.5238
Epoch 3: val_loss did not improve from 1.51646
F1 Score: 0.3312218966143593
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.3692 - loss: 1.6115 - val_accuracy: 0.4515 - val_loss: 1.5404
Epoch 4/20
2475/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3909 - loss: 1.4848
Epoch 4: val_loss did not improve from 1.51646
F1 Score: 0.32683529567853475
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.3936 - loss: 1.4736 - val_accuracy: 0.4003 - val_loss: 1.5191
Epoch 5/20
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4290 - loss: 1.2452
Epoch 5: val_loss did not improve from 1.51646
F1 Score: 0.3492957275229478
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.4308 - loss: 1.2698 - val_accuracy: 0.4055 - val_loss: 1.5594
Epoch 6/20
2475/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4475 - loss: 1.2238
Epoch 6: val_loss improved from 1.51646 to 1.29971, saving model to best_model.keras

Epoch 6: finished saving model to best_model.keras
F1 Score: 0.38585697239355055
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.4433 - loss: 1.2605 - val_accuracy: 0.5131 - val_loss: 1.2997
Epoch 7/20
2474/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4640 - loss: 1.1546
Epoch 7: val_loss improved from 1.29971 to 1.27174, saving model to best_model.keras

Epoch 7: finished saving model to best_model.keras
F1 Score: 0.39088439468853964
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.4599 - loss: 1.1329 - val_accuracy: 0.5147 - val_loss: 1.2717
Epoch 8/20
2474/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4723 - loss: 1.1139
Epoch 8: val_loss did not improve from 1.27174
F1 Score: 0.37351258585409597
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.4612 - loss: 1.1561 - val_accuracy: 0.4713 - val_loss: 1.3148
Epoch 9/20
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4730 - loss: 1.0354
Epoch 9: val_loss did not improve from 1.27174
F1 Score: 0.36738633932589565
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.4732 - loss: 1.0585 - val_accuracy: 0.4847 - val_loss: 1.3282
Epoch 10/20
2475/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4807 - loss: 1.0248
Epoch 10: val_loss did not improve from 1.27174
F1 Score: 0.38494431589561917
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.4812 - loss: 1.0749 - val_accuracy: 0.5032 - val_loss: 1.3344
Epoch 11/20
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4796 - loss: 1.0302
Epoch 11: val_loss did not improve from 1.27174
F1 Score: 0.383060384815389
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.4852 - loss: 1.0640 - val_accuracy: 0.5038 - val_loss: 1.3923
Epoch 12/20
2474/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4940 - loss: 1.0758
Epoch 12: val_loss improved from 1.27174 to 1.19932, saving model to best_model.keras

Epoch 12: finished saving model to best_model.keras
F1 Score: 0.3865583935014821
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.4995 - loss: 1.0411 - val_accuracy: 0.5301 - val_loss: 1.1993
Epoch 13/20
2474/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5026 - loss: 0.9762
Epoch 13: val_loss did not improve from 1.19932
F1 Score: 0.38975303286889695
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.4998 - loss: 0.9914 - val_accuracy: 0.5320 - val_loss: 1.2131
Epoch 14/20
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5072 - loss: 0.9510
Epoch 14: val_loss improved from 1.19932 to 1.17174, saving model to best_model.keras

Epoch 14: finished saving model to best_model.keras
F1 Score: 0.4118426032639488
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.5066 - loss: 0.9632 - val_accuracy: 0.5610 - val_loss: 1.1717
Epoch 15/20
2474/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5036 - loss: 1.0852
Epoch 15: val_loss did not improve from 1.17174
F1 Score: 0.4110995131668691
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.4968 - loss: 1.0820 - val_accuracy: 0.5395 - val_loss: 1.1946
Epoch 16/20
2474/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5072 - loss: 0.9617
Epoch 16: val_loss improved from 1.17174 to 1.16603, saving model to best_model.keras

Epoch 16: finished saving model to best_model.keras
F1 Score: 0.4015915874350196
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.5058 - loss: 0.9907 - val_accuracy: 0.5410 - val_loss: 1.1660
Epoch 17/20
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5111 - loss: 0.9357
Epoch 17: val_loss did not improve from 1.16603
F1 Score: 0.39881459873084707
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.5098 - loss: 0.9473 - val_accuracy: 0.5508 - val_loss: 1.1705
Epoch 18/20
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5205 - loss: 0.8719
Epoch 18: val_loss did not improve from 1.16603
F1 Score: 0.42552055022613233
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.5187 - loss: 0.9307 - val_accuracy: 0.5568 - val_loss: 1.1792
Epoch 19/20
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5176 - loss: 0.9804
Epoch 19: val_loss improved from 1.16603 to 1.15873, saving model to best_model.keras

Epoch 19: finished saving model to best_model.keras
F1 Score: 0.42463957722652396
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.5196 - loss: 0.9879 - val_accuracy: 0.5629 - val_loss: 1.1587
Epoch 20/20
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5271 - loss: 0.9145
Epoch 20: val_loss did not improve from 1.15873
F1 Score: 0.39638824393358957
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 58s 23ms/step - accuracy: 0.5208 - loss: 1.0056 - val_accuracy: 0.5515 - val_loss: 1.2133

In [ ]:
from tensorflow.keras.models import load_model

best_model = load_model('best_model.keras')

In [ ]:
from sklearn.metrics import classification_report
import numpy as np

y_pred = np.argmax(best_model.predict(x_test_pad), axis=-1)
print(classification_report(y_problem_test, y_pred))

# issue

In [ ]:
inputs = Input(shape=(x_train_pad.shape[1],))

X = Embedding(input_dim=vocab_size,output_dim=embedding_dim, weights=[embedding_matrix],trainable=False)(inputs)

x1 = Bidirectional(LSTM(128))(X)
x1 = Dropout(0.30)(x1)

x2 = Dense(128,activation="relu")(x1)
x2 = Dropout(0.30)(x2)

x3 = Dense(64,activation="relu")(x2)
x3 = Dropout(0.20)(x3)


Issue_output = Dense(54,activation="softmax",name="issue")(x3)


model = Model(inputs=inputs,outputs=[Issue_output])
model.summary()

In [ ]:
model.compile(optimizer="adam",loss=["sparse_categorical_crossentropy"],metrics=["accuracy"])

In [ ]:
issue_class_weights = compute_class_weight(class_weight="balanced",y=y_issue_train,classes=np.unique(y_issue_train))
print(issue_class_weights)

In [ ]:
classes=np.unique(y_issue_train)
issue_class_weights = dict(zip(classes, issue_class_weights))

In [ ]:
from tensorflow.keras.callbacks import ModelCheckpoint
checkpoint1 = ModelCheckpoint(
    filepath='best_issue_model.keras',  # Where to save the file
    monitor='val_loss',  # Metric to watch
    mode='min',  # 'max' for accuracy, 'min' for loss
    save_best_only=True,  # Only save when the model improves
    verbose=1,
)

In [ ]:
from sklearn.metrics import f1_score

class F1Callback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        pred = np.argmax(self.model.predict(x_test_pad, verbose=0), axis=1)
        f1 = f1_score(y_issue_test, pred, average="macro")
        print("F1 Score:", f1)

In [78]:
model.fit(x_train_pad,y_issue_train,validation_data=(x_test_pad,y_issue_test),class_weight=issue_class_weights,callbacks=[early_stop,checkpoint1,F1Callback()],epochs=30,batch_size=50)

Epoch 1/30
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.1016 - loss: 3.7736
Epoch 1: val_loss improved from None to 2.80912, saving model to best_issue_model.keras

Epoch 1: finished saving model to best_issue_model.keras
F1 Score: 0.06886238301987403
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 61s 23ms/step - accuracy: 0.1177 - loss: 4.0385 - val_accuracy: 0.1561 - val_loss: 2.8091
Epoch 2/30
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.1388 - loss: 3.2243
Epoch 2: val_loss improved from 2.80912 to 2.74046, saving model to best_issue_model.keras

Epoch 2: finished saving model to best_issue_model.keras
F1 Score: 0.07877702161598041
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 56s 23ms/step - accuracy: 0.1401 - loss: 3.4095 - val_accuracy: 0.1584 - val_loss: 2.7405
Epoch 3/30
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.1343 - loss: 3.1414
Epoch 3: val_loss did not improve from 2.74046
F1 Score: 0.07525285499297382
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 56s 23ms/step - accuracy: 0.1367 - loss: 3.2083 - val_accuracy: 0.1355 - val_loss: 2.8397
Epoch 4/30
2474/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.1361 - loss: 2.9261
Epoch 4: val_loss did not improve from 2.74046
F1 Score: 0.08370832856828715
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 57s 23ms/step - accuracy: 0.1398 - loss: 3.1920 - val_accuracy: 0.1364 - val_loss: 2.8405
Epoch 5/30
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.1490 - loss: 3.2280
Epoch 5: val_loss improved from 2.74046 to 2.66681, saving model to best_issue_model.keras

Epoch 5: finished saving model to best_issue_model.keras
F1 Score: 0.10468139085834845
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 57s 23ms/step - accuracy: 0.1526 - loss: 3.0203 - val_accuracy: 0.1870 - val_loss: 2.6668
Epoch 6/30
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.1594 - loss: 2.8302
Epoch 6: val_loss did not improve from 2.66681
F1 Score: 0.09473201381953143
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 56s 23ms/step - accuracy: 0.1559 - loss: 3.0841 - val_accuracy: 0.1741 - val_loss: 2.8267
Epoch 7/30
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.1576 - loss: 3.0246
Epoch 7: val_loss improved from 2.66681 to 2.65640, saving model to best_issue_model.keras

Epoch 7: finished saving model to best_issue_model.keras
F1 Score: 0.10664776450575052
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 56s 23ms/step - accuracy: 0.1589 - loss: 3.0160 - val_accuracy: 0.1828 - val_loss: 2.6564
Epoch 8/30
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.1621 - loss: 2.9166
Epoch 8: val_loss did not improve from 2.65640
F1 Score: 0.09922929498516969
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 56s 23ms/step - accuracy: 0.1575 - loss: 2.8956 - val_accuracy: 0.1696 - val_loss: 2.6965
Epoch 9/30
2475/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.1564 - loss: 2.9689
Epoch 9: val_loss did not improve from 2.65640
F1 Score: 0.10900496390943097
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 56s 23ms/step - accuracy: 0.1568 - loss: 2.8517 - val_accuracy: 0.1842 - val_loss: 2.6782
Epoch 10/30
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.1652 - loss: 2.7279
Epoch 10: val_loss improved from 2.65640 to 2.63751, saving model to best_issue_model.keras

Epoch 10: finished saving model to best_issue_model.keras
F1 Score: 0.11244617729472871
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 56s 23ms/step - accuracy: 0.1697 - loss: 2.8323 - val_accuracy: 0.1903 - val_loss: 2.6375

In [ ]:
from tensorflow.keras.models import load_model

best_issue_model = load_model('best_issue_model.keras')

In [ ]:
from sklearn.metrics import classification_report
import numpy as np

y_pred = np.argmax(best_issue_model.predict(x_test_pad), axis=-1)
print(classification_report(y_issue_test, y_pred))

# Subissue

In [81]:
inputs = Input(shape=(x_train_pad.shape[1],))

X = Embedding(input_dim=vocab_size,output_dim=embedding_dim, weights=[embedding_matrix],trainable=False)(inputs)

x1 = Bidirectional(LSTM(128))(X)
x1 = Dropout(0.30)(x1)

x2 = Dense(128,activation="relu")(x1)
x2 = Dropout(0.30)(x2)

x3 = Dense(64,activation="relu")(x2)
x3 = Dropout(0.20)(x3)


SubIssue_output=Dense(244,activation="softmax",name="subissue")(x3)


model = Model(inputs=inputs,outputs=[SubIssue_output])
model.summary()

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_2 (InputLayer)      │ (None, 200)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ embedding_2 (Embedding)         │ (None, 200, 100)       │     4,000,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 256)            │       234,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ subissue (Dense)                │ (None, 244)            │        15,860 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,291,508 (16.37 MB)

 Trainable params: 291,508 (1.11 MB)

 Non-trainable params: 4,000,000 (15.26 MB)

In [82]:
model.compile(optimizer="adam",loss=["sparse_categorical_crossentropy"],metrics=["accuracy"])

In [83]:
subissue_class_weights = compute_class_weight(class_weight="balanced",y=y_subissue_train,classes=np.unique(y_subissue_train))
print(subissue_class_weights)

[6.12150640e-02 2.18576852e+00 3.64294753e+00 1.35172527e+01
 3.95119694e+01 7.40885045e-02 9.17242146e+00 3.61729297e+00
 4.10924481e+00 1.29059196e+00 2.59422021e+00 3.24277526e-01
 2.70345054e+01 5.83037005e-01 1.23772434e+00 8.76545395e-01
 4.17606180e+00 2.33479819e+01 1.07011584e+01 4.66959638e+01
 5.62601973e-01 3.95119694e+01 1.02731120e+02 6.84874136e+00
 2.56827801e+02 2.70345054e+00 1.83448429e+01 8.56092669e+01
 9.99329964e-01 5.13655602e+02 3.74931096e+00 1.35887725e+00
 1.20860142e+00 3.10178503e-01 2.49347379e+00 7.90239387e+00
 9.33919276e+00 3.66896858e+01 1.25281854e+01 6.18862171e+00
 7.21426407e-01 5.83699547e+00 8.56092669e+01 3.37931317e+00
 3.21436547e-01 8.56092669e+01 3.66896858e+01 1.02731120e+02
 1.90242815e+01 1.38451645e+00 4.28046335e+00 7.33793717e+00
 6.42069502e+01 4.66959638e+01 1.51075177e+01 8.56092669e+01
 8.42058363e+00 8.56092669e+01 1.22298953e+01 2.56827801e+01
 1.39202060e-01 1.97559847e+00 2.93517487e+00 7.44428408e+00
 1.11084689e-01 2.05462241e+01 5.13655602e+02 7.22441071e-01
 1.53881247e-01 5.03583923e+00 1.58535680e+00 1.42682112e+01
 2.78253305e-01 3.17659618e-01 3.21034751e+01 5.77141125e+00
 4.84580756e+00 5.70728446e+00 1.02731120e+02 2.73221065e+00
 1.75849230e-01 8.02586878e+00 2.56827801e+02 1.20576432e+00
 4.23808252e-01 5.42976323e-01 2.71775451e+00 2.46949808e+00
 3.52543309e-01 3.66896858e+01 7.44428408e+00 1.16739909e+01
 5.62601973e-01 2.44597906e+01 1.29384283e+00 3.92103513e+00
 4.80051964e+00 1.09288426e+01 1.31706565e+01 4.66959638e+01
 2.40025982e+00 4.89195811e+00 6.67085197e-01 5.52317851e+00
 4.48607512e-01 8.42058363e-01 3.02150354e+01 5.13655602e+02
 2.85364223e+01 2.44597906e+01 3.83325076e+00 1.71218534e+01
 6.42069502e+01 5.77141125e+00 4.97873027e-02 4.84580756e+00
 5.31184697e-01 2.33479819e+01 1.25281854e+01 2.59029552e-01
 5.13655602e+02 1.02731120e+02 1.97559847e+01 5.77141125e+00
 3.74931096e+00 1.42682112e+01 3.44735303e+00 1.51075177e+01
 1.19454791e+01 2.70345054e+00 2.37803519e+00 7.33793717e+01
 9.87799234e+00 4.66959638e+01 1.58047877e+00 1.46758743e+01
 2.88570563e+00 2.14023167e+01 4.46657045e+00 3.20633959e-01
 4.46268985e-01 5.50541910e-01 1.71218534e+02 3.15126136e+00
 1.02731120e+02 2.52286641e-01 5.03583923e+00 5.13655602e+02
 1.03351228e+00 2.57988750e-01 5.40690107e+00 1.22298953e+01
 7.16395539e-01 7.33793717e+01 2.85364223e+01 1.60517376e+00
 4.01293439e-01 2.56827801e+02 6.26409270e+00 1.15949346e+00
 1.11664261e+01 9.15607133e-01 9.87799234e+00 3.26545201e-01
 1.55653213e+01 2.85364223e+01 1.02731120e+01 1.02731120e+02
 1.71218534e+02 3.42437068e+01 2.59422021e+00 2.71775451e+00
 1.25281854e+01 3.21034751e+01 1.36610532e+00 4.28046335e+01
 3.61220536e-01 2.41152865e+00 2.85364223e+01 9.17242146e+00
 3.59199721e+00 4.24508762e-01 2.83787625e+00 1.71218534e+01
 1.33417039e+00 2.05462241e+01 3.69536404e+00 3.42437068e+01
 3.98800933e-01 5.13655602e+02 2.56827801e+02 2.14023167e+01
 2.06287390e+00 4.54562479e+00 5.52317851e+00 3.56705279e+00
 5.16808131e-02 3.51818905e+00 2.21403277e+00 1.31706565e+01
 3.19040746e+00 1.02731120e+02 3.21034751e+01 5.13655602e+01
 1.90242815e+01 3.56705279e+00 6.67085197e+00 3.92103513e+00
 1.97559847e+01 4.38347501e-02 1.28413900e+01 6.46921413e-01
 9.01150178e+00 1.04827674e+01 1.82795588e+00 7.90239387e+00
 2.56827801e+02 1.51075177e+01 3.18644914e-01 8.02586878e+00
 1.97559847e+01 1.22298953e+01 1.04827674e+01 3.66896858e+01
 1.71218534e+02 4.89195811e+00 2.07957733e+00 2.56827801e+01
 1.22298953e+00 8.69129614e-01 5.70728446e+00 6.42069502e+00
 1.52873691e+00 1.63065270e+00 2.09655348e+00 3.83325076e+00
 1.60517376e+01 1.55653213e+01 5.19894334e-01 3.31390711e+00
 1.46340627e+00]

In [84]:
classes=np.unique(y_subissue_train)
subissue_class_weights = dict(zip(classes, subissue_class_weights))

In [85]:
from tensorflow.keras.callbacks import ModelCheckpoint
checkpoint2 = ModelCheckpoint(
    filepath='best_subissue_model.keras',  # Where to save the file
    monitor='val_loss',  # Metric to watch
    mode='min',  # 'max' for accuracy, 'min' for loss
    save_best_only=True,  # Only save when the model improves
    verbose=1,
)

In [86]:
from sklearn.metrics import f1_score

class F1Callback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        pred = np.argmax(self.model.predict(x_test_pad, verbose=0), axis=1)
        f1 = f1_score(y_subissue_test, pred, average="macro")
        print("F1 Score:", f1)

In [87]:
model.fit(x_train_pad,y_subissue_train,validation_data=(x_test_pad,y_subissue_test),class_weight=subissue_class_weights,callbacks=[early_stop,checkpoint2,F1Callback()],epochs=50,batch_size=50)

Epoch 1/50
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.0336 - loss: 5.4866
Epoch 1: val_loss improved from None to 5.16572, saving model to best_subissue_model.keras

Epoch 1: finished saving model to best_subissue_model.keras
F1 Score: 0.003273385725018171
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 60s 23ms/step - accuracy: 0.0393 - loss: 5.4968 - val_accuracy: 0.0337 - val_loss: 5.1657
Epoch 2/50
2475/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.0453 - loss: 5.3634
Epoch 2: val_loss improved from 5.16572 to 4.66124, saving model to best_subissue_model.keras

Epoch 2: finished saving model to best_subissue_model.keras
F1 Score: 0.0076121038904166894
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 57s 23ms/step - accuracy: 0.0437 - loss: 5.4133 - val_accuracy: 0.0510 - val_loss: 4.6612
Epoch 3/50
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.0472 - loss: 5.3079
Epoch 3: val_loss improved from 4.66124 to 4.53159, saving model to best_subissue_model.keras

Epoch 3: finished saving model to best_subissue_model.keras
F1 Score: 0.007588287461815758
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 57s 23ms/step - accuracy: 0.0492 - loss: 5.2888 - val_accuracy: 0.0576 - val_loss: 4.5316
Epoch 4/50
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.0506 - loss: 5.1093
Epoch 4: val_loss did not improve from 4.53159
F1 Score: 0.005781716111908032
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 57s 23ms/step - accuracy: 0.0507 - loss: 5.1768 - val_accuracy: 0.0495 - val_loss: 5.3398
Epoch 5/50
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.0530 - loss: 5.4059
Epoch 5: val_loss did not improve from 4.53159
F1 Score: 0.008700520651957871
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 57s 23ms/step - accuracy: 0.0508 - loss: 5.2133 - val_accuracy: 0.0559 - val_loss: 4.5847
Epoch 6/50
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.0471 - loss: 4.9760
Epoch 6: val_loss did not improve from 4.53159
F1 Score: 0.009773372460632073
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 57s 23ms/step - accuracy: 0.0461 - loss: 5.1305 - val_accuracy: 0.0486 - val_loss: 4.5906
Epoch 7/50
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.0452 - loss: 4.8805
Epoch 7: val_loss improved from 4.53159 to 4.44555, saving model to best_subissue_model.keras

Epoch 7: finished saving model to best_subissue_model.keras
F1 Score: 0.010151081396367511
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 57s 23ms/step - accuracy: 0.0439 - loss: 5.0484 - val_accuracy: 0.0538 - val_loss: 4.4456
Epoch 8/50
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.0501 - loss: 4.8525
Epoch 8: val_loss did not improve from 4.44555
F1 Score: 0.008815682175184353
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 57s 23ms/step - accuracy: 0.0507 - loss: 5.0014 - val_accuracy: 0.0460 - val_loss: 4.7672
Epoch 9/50
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.0482 - loss: 4.8959
Epoch 9: val_loss did not improve from 4.44555
F1 Score: 0.008276147188545212
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 57s 23ms/step - accuracy: 0.0456 - loss: 4.9405 - val_accuracy: 0.0208 - val_loss: 4.5755
Epoch 10/50
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.0420 - loss: 4.8720
Epoch 10: val_loss improved from 4.44555 to 4.44242, saving model to best_subissue_model.keras

Epoch 10: finished saving model to best_subissue_model.keras
F1 Score: 0.00932027296747734
2476/2476 ━━━━━━━━━━━━━━━━━━━━ 57s 23ms/step - accuracy: 0.0434 - loss: 4.9729 - val_accuracy: 0.0375 - val_loss: 4.4424

In [88]:
from tensorflow.keras.models import load_model

best_subissue_model = load_model('best_subissue_model.keras')

In [89]:
from sklearn.metrics import classification_report
import numpy as np

y_pred = np.argmax(best_subissue_model.predict(x_test_pad), axis=-1)
print(classification_report(y_subissue_test, y_pred))

968/968 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      2065
           1       0.00      0.00      0.00        59
           2       0.00      0.00      0.00        36
           3       0.00      0.00      0.00         9
           4       0.00      0.00      0.00         2
           5       0.09      0.00      0.00      1763
           6       0.00      0.00      0.00        12
           7       0.00      0.00      0.00        44
           8       0.00      0.00      0.00        33
           9       0.00      0.00      0.00        98
          10       0.00      0.00      0.00        53
          11       0.00      0.00      0.00       417
          12       0.00      0.00      0.00         2
          13       0.00      0.00      0.00       230
          14       0.00      0.00      0.00       112
          15       0.00      0.00      0.00         1
          16       0.00      0.00      0.00       111
          17       0.00      0.00      0.00        20
          18       0.00      0.00      0.00         8
          19       0.00      0.00      0.00        14
          20       0.00      0.00      0.00         2
          21       0.00      0.00      0.00       210
          22       0.00      0.33      0.00         3
          23       0.00      0.00      0.00         1
          24       0.00      0.00      0.00        10
          25       0.00      0.00      0.00         2
          26       0.00      0.00      0.00        34
          27       0.00      0.00      0.00         3
          28       0.00      0.00      0.00         3
          29       0.00      0.00      0.00       152
          31       0.05      0.04      0.04        27
          32       0.13      0.04      0.07        93
          33       0.00      0.00      0.00        91
          34       0.00      0.00      0.00       399
          35       0.01      0.03      0.01        37
          36       0.00      0.00      0.00        27
          37       0.00      0.00      0.00        14
          38       0.00      0.00      0.00         1
          39       0.00      0.00      0.00        14
          40       0.00      0.41      0.00        17
          41       0.00      0.00      0.00       167
          42       0.00      0.00      0.00        33
          43       0.00      0.00      0.00         3
          44       0.00      0.00      0.00        35
          45       0.00      0.00      0.00       432
          46       0.00      0.00      0.00         2
          47       0.00      0.00      0.00         7
          48       0.00      0.00      0.00         1
          49       0.00      0.00      0.00         6
          50       0.00      0.00      0.00        97
          51       0.00      0.00      0.00        27
          52       0.02      0.10      0.03        10
          53       0.00      0.00      0.00         4
          54       0.00      0.00      0.00         6
          55       0.00      0.00      0.00         7
          56       0.00      0.00      0.00         1
          57       0.00      0.00      0.00        14
          58       0.00      0.00      0.00         1
          59       0.00      0.00      0.00         8
          60       0.00      0.00      0.00         5
          61       0.00      0.00      0.00       911
          62       0.02      0.13      0.04        55
          63       0.00      0.00      0.00        42
          64       0.00      0.00      0.00        30
          65       0.38      0.01      0.03      1111
          66       0.00      0.00      0.00         5
          68       0.00      0.00      0.00       175
          69       0.00      0.00      0.00       896
          70       0.03      0.18      0.04        28
          71       0.00      0.00      0.00        92
          72       0.00      0.62      0.00         8
          73       0.00      0.00      0.00       439
          74       0.36      0.12      0.18       399
          75       0.00      0.00      0.00         7
          76       0.01      0.04      0.01        27
          77       0.00      0.00      0.00        18
          78       0.00      0.00      0.00        24
          79       0.00      0.00      0.00         2
          80       0.00      0.00      0.00        43
          81       0.00      0.00      0.00       729
          82       0.00      0.00      0.00        10
          83       0.00      0.00      0.00         2
          84       0.00      0.00      0.00        91
          85       0.02      0.00      0.01       291
          86       0.02      0.03      0.02       252
          87       0.00      0.04      0.01        46
          88       0.00      0.00      0.00        40
          89       0.00      0.00      0.00       357
          90       0.00      0.00      0.00         5
          91       0.00      0.00      0.00        12
          92       0.01      0.11      0.01         9
          93       0.00      0.00      0.00       219
          94       0.00      0.00      0.00         7
          95       0.11      0.14      0.13        90
          96       0.00      0.00      0.00        31
          97       0.00      0.00      0.00        27
          98       0.00      0.00      0.00         9
          99       0.00      0.67      0.00         9
         100       0.01      0.33      0.03         3
         101       0.00      0.00      0.00        54
         102       0.00      0.00      0.00        31
         103       0.00      0.00      0.00       168
         104       0.00      0.00      0.00        15
         105       0.00      0.00      0.00       291
         106       0.03      0.02      0.02       149
         107       0.00      0.00      0.00         2
         109       0.00      0.00      0.00         3
         110       0.00      0.00      0.00         6
         111       0.00      0.00      0.00        33
         112       0.00      0.00      0.00         4
         113       0.00      0.00      0.00         2
         114       0.00      0.00      0.00        29
         115       0.42      0.01      0.01      2500
         116       0.00      0.00      0.00        35
         117       0.06      0.00      0.01       222
         118       0.00      0.20      0.00         5
         119       0.00      0.00      0.00        14
         120       0.05      0.03      0.04       502
         121       0.00      0.00      0.00         1
         124       0.00      0.00      0.00         5
         125       0.00      0.00      0.00        18
         126       0.00      0.00      0.00        33
         127       0.00      0.00      0.00         5
         128       0.00      0.00      0.00        34
         129       0.00      0.00      0.00         9
         130       0.00      0.00      0.00         9
         131       0.00      0.00      0.00        36
         132       0.00      0.00      0.00         1
         133       0.00      0.00      0.00        77
         134       0.00      0.00      0.00         0
         135       0.00      0.00      0.00        12
         136       0.00      0.00      0.00         2
         137       0.00      0.00      0.00        83
         138       0.00      0.00      0.00         5
         139       0.00      0.00      0.00        50
         140       0.00      0.00      0.00         7
         141       0.00      0.00      0.00        26
         142       0.04      0.01      0.02       378
         143       0.00      0.00      0.00       265
         144       0.07      0.05      0.05       232
         145       0.00      0.00      0.00         3
         146       0.00      0.00      0.00        38
         147       0.00      0.00      0.00         2
         148       0.97      0.50      0.66       477
         149       0.00      0.00      0.00        29
         151       0.00      0.00      0.00       145
         152       0.10      0.33      0.16       525
         153       0.03      0.06      0.04        17
         154       0.00      0.00      0.00        11
         155       0.00      0.00      0.00       207
         156       0.00      0.00      0.00         1
         157       0.00      0.00      0.00         5
         158       0.03      0.01      0.02        67
         159       0.00      0.00      0.00       302
         160       0.00      0.00      0.00         1
         161       0.00      0.00      0.00        20
         162       0.01      0.10      0.03       105
         163       0.00      0.00      0.00         9
         164       0.00      0.00      0.00       159
         165       0.00      0.00      0.00        19
         166       0.00      0.00      0.00       394
         167       0.01      0.15      0.01        13
         168       0.00      0.00      0.00         3
         169       0.00      0.00      0.00        14
         170       0.00      0.00      0.00         0
         172       0.00      0.00      0.00         7
         173       0.00      0.00      0.00        35
         174       0.00      0.00      0.00        46
         175       0.00      0.00      0.00         9
         176       0.00      0.00      0.00         3
         177       0.00      0.00      0.00        77
         178       0.00      0.00      0.00         2
         179       0.00      0.00      0.00       333
         180       0.00      0.00      0.00        46
         181       0.00      0.00      0.00         3
         182       0.00      0.00      0.00        15
         183       0.00      0.00      0.00        43
         184       0.00      0.00      0.00       271
         185       0.01      0.02      0.01        47
         186       0.00      0.00      0.00         6
         187       0.05      0.01      0.02        97
         188       0.00      0.00      0.00         3
         189       0.00      0.00      0.00        40
         190       0.00      0.00      0.00         5
         191       0.05      0.01      0.02       325
         194       0.00      0.00      0.00         2
         195       0.00      0.00      0.00        69
         196       0.00      0.00      0.00        41
         197       0.00      0.00      0.00        30
         198       0.00      0.17      0.01        42
         199       0.71      0.18      0.29      2570
         200       0.00      0.00      0.00        36
         201       0.00      0.00      0.00        47
         202       0.00      0.00      0.00        10
         203       0.00      0.00      0.00        45
         205       0.00      0.00      0.00         8
         206       0.00      0.00      0.00         3
         207       0.00      0.00      0.00         5
         208       0.00      0.00      0.00        55
         209       0.00      0.00      0.00        20
         210       0.00      0.00      0.00        35
         211       0.00      0.00      0.00         7
         212       0.26      0.02      0.04      3020
         213       0.01      0.10      0.01        10
         214       0.00      0.00      0.00       204
         215       0.00      0.00      0.00        13
         216       0.00      0.00      0.00        10
         217       0.00      0.00      0.00        74
         218       0.00      0.00      0.00        11
         220       0.00      0.00      0.00         9
         221       0.00      0.00      0.00       408
         222       0.00      0.00      0.00        19
         223       0.00      0.00      0.00         6
         224       0.00      0.00      0.00        13
         225       0.00      0.00      0.00         8
         226       0.00      0.00      0.00         3
         228       0.00      0.00      0.00        25
         229       0.00      0.00      0.00        74
         230       0.00      0.00      0.00         4
         231       0.00      0.00      0.00       121
         232       0.00      0.00      0.00       152
         233       0.00      0.00      0.00        30
         234       0.00      0.00      0.00        26
         235       0.00      0.00      0.00        89
         236       0.00      0.00      0.00        94
         237       0.00      0.00      0.00        62
         238       0.00      0.00      0.00        34
         239       0.00      0.00      0.00         9
         240       0.00      0.00      0.00         8
         241       0.11      0.01      0.01       253
         242       0.00      0.00      0.00        54
         243       0.00      0.00      0.00       102

    accuracy                           0.04     30948
   macro avg       0.02      0.02      0.01     30948
weighted avg       0.16      0.04      0.05     30948

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# prediction

In [90]:
def predict_problem(complaint):

    cleaned = text_preprocessing(complaint)

    sequences = tokenizer.texts_to_sequences([cleaned])

    padded = pad_sequences(sequences,maxlen=200,padding="pre",truncating="post")

    probability = best_model.predict(padded, verbose=0)

    return probability

In [91]:
prediction=predict_problem("my credit has an issue during transaction like my balancing deducted my account but payment is not done")
prediction

array([[6.8355255e-02, 3.9224780e-01, 3.8385555e-01, 1.6403604e-02,
        3.4224223e-02, 6.0480740e-02, 9.8196659e-03, 1.1693995e-04,
        3.0005421e-04, 1.1575210e-03, 2.1445677e-03, 3.0894073e-02]],
      dtype=float32)

In [92]:
predicted_class = np.argmax(prediction,axis=1)

print("Predicted class number:", predicted_class)

print("Predicted label:", le_problem.inverse_transform([predicted_class]))

Predicted class number: [1]
Predicted label: ['Credit card']

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [93]:
def predict_issue_problem(complaint):

    cleaned = text_preprocessing(complaint)

    sequences = tokenizer.texts_to_sequences([cleaned])

    padded = pad_sequences(sequences,maxlen=200,padding="pre",truncating="post")

    probability = best_issue_model.predict(padded, verbose=0)

    return probability

In [94]:
prediction=predict_issue_problem("my credit has an issue during transaction like my balancing deducted my account but payment is not done")
prediction

array([[5.38166100e-03, 5.56165092e-02, 1.04842089e-04, 1.22053828e-02,
        1.75709336e-09, 1.92482350e-03, 6.53288134e-06, 9.36705545e-02,
        4.61624376e-03, 4.15511662e-03, 6.62878230e-02, 1.11434187e-04,
        8.83875691e-05, 2.84343865e-03, 2.74683326e-03, 1.28219090e-02,
        6.11984991e-02, 6.55619204e-02, 2.47312664e-06, 8.60602886e-04,
        5.22059985e-02, 1.10042914e-04, 9.41552967e-03, 2.98909005e-02,
        4.47201981e-13, 5.08627203e-11, 3.07353912e-03, 1.05863123e-03,
        4.42485791e-03, 6.14391826e-02, 3.23565770e-03, 1.59485836e-03,
        6.31006211e-02, 4.06460725e-02, 2.30317451e-02, 3.16812024e-02,
        8.47402029e-03, 2.37197871e-03, 6.79385960e-02, 1.93460932e-04,
        5.31923215e-05, 3.18729319e-04, 1.51998238e-05, 5.30546755e-02,
        1.69315899e-04, 7.58455499e-05, 1.08372769e-03, 1.56701799e-03,
        7.61570502e-03, 3.71758419e-04, 6.11087540e-04, 1.09140806e-01,
        1.97160523e-02, 1.21149458e-02]], dtype=float32)

In [95]:
predicted_class = prediction.argmax()

print("Predicted class number:", predicted_class)

print("Predicted label:", le_issue.inverse_transform([predicted_class])[0])

Predicted class number: 51
Predicted label: Trouble using your card

In [96]:
def predict_subissue_problem(complaint):

    cleaned = text_preprocessing(complaint)

    sequences = tokenizer.texts_to_sequences([cleaned])

    padded = pad_sequences(sequences,maxlen=200,padding="pre",truncating="post")

    probability = best_subissue_model.predict(padded, verbose=0)

    return probability

In [97]:
prediction=predict_subissue_problem("my credit has an issue during transaction like my balancing deducted my account but payment is not done")
prediction

array([[8.51133559e-03, 8.98153987e-03, 9.63384658e-03, 7.49413273e-04,
        5.70779433e-03, 8.91312398e-03, 6.60177227e-03, 9.90735716e-04,
        6.68538269e-03, 1.52464416e-02, 1.73506938e-04, 6.18499843e-03,
        1.28991614e-05, 4.93158121e-03, 1.28363790e-02, 4.08579504e-10,
        3.30583984e-03, 2.32062908e-03, 6.89491106e-04, 3.95080633e-03,
        2.09628328e-04, 8.05807393e-03, 8.27680591e-09, 5.53225838e-08,
        6.19483471e-05, 2.58944908e-07, 3.28389299e-03, 1.38281292e-04,
        3.03211692e-07, 1.19765196e-02, 6.02385086e-10, 3.89653700e-03,
        1.06347464e-02, 1.07384697e-02, 8.09599180e-03, 1.57048344e-03,
        1.30716231e-04, 3.60189762e-04, 2.83021736e-03, 5.81431595e-05,
        6.41224859e-03, 5.21640526e-03, 2.22217222e-03, 2.09720966e-07,
        3.77135701e-03, 8.71641934e-03, 2.28122005e-07, 1.44530705e-03,
        6.50306401e-06, 1.30072627e-02, 1.14181554e-02, 6.43681455e-03,
        8.58517829e-03, 1.00060995e-03, 2.30563205e-06, 8.64256799e-05,
        1.21521339e-06, 6.82514068e-03, 1.07759980e-07, 1.08533644e-03,
        1.06022228e-02, 7.50296842e-03, 1.31765930e-02, 1.12076178e-02,
        1.17200240e-02, 6.49960339e-03, 7.78780395e-06, 1.64143610e-09,
        3.82553972e-03, 7.07724923e-03, 1.04511110e-02, 6.04924420e-03,
        5.41375950e-04, 5.67888562e-03, 7.61346333e-03, 9.59670885e-08,
        1.93162262e-02, 1.52545224e-04, 2.98637569e-05, 4.24302234e-05,
        2.54876772e-03, 2.94848811e-03, 9.78962169e-04, 3.03829795e-10,
        6.26073033e-03, 5.08622499e-03, 4.37341398e-03, 1.35511700e-02,
        2.03527394e-03, 1.21039655e-02, 1.93180540e-06, 7.95061060e-04,
        8.11175443e-03, 5.87708782e-04, 1.39351713e-03, 1.84812990e-03,
        1.40231673e-03, 4.31307871e-03, 2.78820735e-05, 1.09038808e-06,
        6.04958180e-03, 3.73469084e-04, 9.81237553e-03, 4.22740541e-03,
        4.06596670e-03, 3.12856748e-03, 2.96575739e-03, 5.01341419e-04,
        4.53835684e-11, 1.73292807e-04, 1.03946722e-05, 4.84516332e-03,
        1.70390587e-03, 2.00461844e-04, 1.11858910e-02, 7.42589030e-03,
        1.28745036e-02, 1.15047591e-02, 1.96849853e-02, 6.07344729e-04,
        7.26128742e-03, 4.30680963e-10, 1.07317488e-10, 4.95028125e-08,
        4.28780686e-06, 1.82489224e-03, 3.02298879e-03, 6.63089959e-05,
        3.61620053e-03, 7.19194795e-05, 9.35150497e-03, 1.66416424e-03,
        3.98953426e-10, 2.17207265e-03, 1.02786623e-06, 1.57109942e-04,
        7.76509978e-07, 2.90112244e-03, 2.55419803e-03, 2.67410860e-03,
        3.59225116e-04, 1.00053586e-02, 7.97992107e-03, 1.03341052e-02,
        1.49879633e-02, 6.25698760e-07, 4.41640709e-03, 1.90508901e-03,
        1.18374825e-03, 6.16224890e-04, 7.60036062e-11, 2.82880245e-03,
        5.80075383e-03, 1.51824532e-02, 9.37456389e-06, 6.67046104e-03,
        4.98269969e-07, 6.02785949e-05, 1.60676111e-02, 6.86842855e-03,
        6.80588308e-10, 1.30186733e-02, 1.44366706e-02, 1.71568734e-03,
        4.08459734e-03, 6.52630581e-04, 3.56580480e-03, 7.45585887e-04,
        1.51419022e-06, 1.36268238e-04, 2.88395358e-06, 5.43788292e-10,
        3.15101672e-04, 1.61489879e-03, 6.07037265e-03, 3.57054942e-03,
        7.85916403e-04, 9.09108389e-03, 4.77661466e-04, 5.63714700e-03,
        3.09900846e-03, 2.52312951e-04, 3.59224388e-03, 1.66689930e-03,
        1.09542673e-02, 1.81478672e-02, 5.74054488e-04, 6.32162439e-03,
        2.12397752e-03, 1.82093109e-03, 4.04217804e-04, 6.84264395e-03,
        2.11439000e-09, 2.58659327e-07, 2.51289981e-04, 1.85044715e-03,
        1.67441238e-02, 1.56743862e-02, 9.25238710e-03, 4.58461652e-03,
        3.40729486e-03, 2.47531664e-03, 8.47357791e-04, 1.52443470e-02,
        1.91910118e-07, 1.33292473e-04, 1.86030240e-06, 1.30192679e-03,
        2.88232695e-03, 8.16624425e-03, 6.00781851e-03, 5.63461275e-04,
        7.42053147e-03, 5.57245112e-05, 7.52016110e-03, 3.47027578e-03,
        1.14530558e-03, 3.99253843e-03, 9.43201303e-04, 1.55201885e-09,
        5.57843735e-03, 4.67091985e-03, 8.29990022e-03, 1.56558747e-03,
        2.67558871e-03, 4.09946730e-03, 1.25160223e-04, 5.21113134e-06,
        3.87173495e-03, 6.83987804e-04, 1.61931894e-05, 2.56026629e-04,
        2.79396726e-03, 2.89381156e-03, 2.36739201e-04, 9.22656152e-03,
        1.38982560e-03, 7.24574132e-03, 3.04168789e-03, 1.46650244e-04,
        1.85211480e-03, 7.50654936e-03, 1.47151174e-02, 2.90513993e-03]],
      dtype=float32)

In [98]:
predicted_class = prediction.argmax(axis=1)[0]

print("Predicted class number:", predicted_class)

print("Predicted label:", le_subissue.inverse_transform([predicted_class])[0])

Predicted class number: 118
Predicted label: Information that should be on the report is missing

In [110]:
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

In [ ]:
import pickle 
with open(r"C:\Users\PRAVALLIKA\Downloads\nlp\nlp.pkl","wb") as f:
    pickle.dump(tokenizer,f)

In [ ]:
model.save(r"C:\Users\PRAVALLIKA\Downloads\nlp\nlpmodel.keras")

In [ ]:
with open("label_encoders.pkl", "wb") as f:
    pickle.dump({
        "problem": le_problem,
        "issue": le_issue,
        "subissue": le_subissue
    }, f)

print("Model and preprocessing objects saved successfully!")

# Hyperparameter Tuning

In [ ]:
from keras.models import load_model
deployment=load_model(r"C:\Users\PRAVALLIKA\Downloads\nlp\nlpmodel.keras")

# Bayesian Optuna

import optuna 
from keras.layers import LeakyReLU,PReLU
from keras.optimizers import SGD,Adagrad,RMSprop,Adam
from keras.layers import BatchNormalization

def objective(trial):

    lstm_units = trial.suggest_int('lstm_units', 64, 256)

    n_layers = trial.suggest_int('n_layers', 1, 10)

    epochs = trial.suggest_int('epochs', 1, 100)

    learn_rate = trial.suggest_float('learning_rate', 1e-4, 1e-2)

    batch_size = trial.suggest_int('batch_size', 6, 128)

    activation = trial.suggest_categorical('activation',["sigmoid", "tanh", "relu"])

    optimizers = trial.suggest_categorical('optimizers',['SGD', 'Adagrad', 'RMSprop', 'Adam'])

    dropout1 = trial.suggest_float('dropout1', 0.1, 0.5)


    inputs = Input(shape=(x_train_pad.shape[1],))


    X = Embedding(input_dim=vocab_size,output_dim=embedding_dim,weights=[embedding_matrix],trainable=False)(inputs)


    x1 = Bidirectional(LSTM(lstm_units))(X)

    x1 = Dropout(dropout1)(x1)


    x3 = x1

    for i in range(n_layers):

        n_units = trial.suggest_int(f'units{i}',32,128)

        x3 = Dense(units=n_units,activation=activation)(x3)


    Problem_output = Dense(5,activation="softmax",name="problem")(x3)


    Issue_output = Dense(98,activation="softmax",name="issue")(x3)


    SubIssue_output = Dense(213,activation="softmax",name="subissue")(x3)


    model = Model(inputs=inputs,outputs=[Problem_output,Issue_output,SubIssue_output])


    if optimizers == 'SGD':

        optimizer = SGD(learning_rate=learn_rate)

    elif optimizers == 'Adagrad':

        optimizer = Adagrad(learning_rate=learn_rate)

    elif optimizers == 'RMSprop':

        optimizer = RMSprop(learning_rate=learn_rate)

    else:

        optimizer = Adam(learning_rate=learn_rate)


    model.compile(optimizer=optimizer,loss=['sparse_categorical_crossentropy','sparse_categorical_crossentropy',
            'sparse_categorical_crossentropy'],
        metrics=['accuracy','accuracy','accuracy'])


    history = model.fit(x_train_pad,[y_problem_train,y_issue_train,y_subissue_train],
            epochs=epochs,batch_size=batch_size,
            validation_data=(x_test_pad,[y_problem_test,y_issue_test,y_subissue_test]),verbose=0)


    problem_accuracy = max(history.history['val_problem_accuracy'])

    issue_accuracy = max(history.history['val_issue_accuracy'])

    subissue_accuracy = max(history.history['val_subissue_accuracy'])


    accuracy = (problem_accuracy +issue_accuracy +subissue_accuracy) / 3


    return accuracy

study = optuna.create_study(direction='maximize')

study.optimize( objective, n_trials=20)

print(study.best_params)

print(study.best_value)